# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb368fb1095df268ddd7bcc80a827935a765741921a11d50314134422230feaf402e7f787f801ca61a081d025de3355f71338a3c2adbd76435ff29fd93063a0

test:
  secret_key_base: 3e0310831576945f7b085697d22453e35a8d854a30fd77a4fdb9174025237f942785453526ca8d974e6cedcc7cc2189571124e1562d077402e64bd80a82ce4a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
